### ISSUE TITLE
expo web support

### ISSUE THREAD

**Issue by fabarea** [kanzitelli/rn-bounceable#3]
I am wondering if expo web support is possible? When running the expo-starter I am facing the following error. I have followed the default installation:

```
npx cli-rn new App
cd App && yarn start
```

In the browser, I get:

```
./node_modules/rn-bounceable/lib/index.js 53:10
Module parse failed: Unexpected token (53:10)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   };
|   const Children = useMemo(
>     () => <Animated.View style={[contentContainerStyle, sz]}>{children}</Animated.View>,
|     [contentContainerStyle, sz, children],
|   );
```

![image](https://user-images.githubusercontent.com/620730/146163448-5af08002-d032-439b-a0c6-6d5f522dc96b.png)

BTW when suppressing the usage of `rn-rebounce`, I stumbled upon the following issue.

![image](https://user-images.githubusercontent.com/620730/146163212-8e937e55-1e24-480a-a802-9b0b95c9e841.png)

**Comment by kanzitelli** [comment]
Hi again @fabarea!

So I have figured out what was causing the problem and it's more about project-level issue. The thing you need add is `webpack.config.js` because Expo Web doesn't transpile modules by default, so we'll need to tell it to transpile the library :)

I have added the explanation in the Readme and also made necessary changes for `expo-starter`, so now if you repeat the steps with `cli-rn`, everything should work as expected.

Here are some links to test with Expo web: https://rn-bounceable.batyr.io and https://expo-starter.batyr.io.

Let me know how it goes!

**Comment by fabarea** [comment]
@kanzitelli Wonderful! It now works as you mentioned.
BTW, your work is very inspiring. Just to let you know.

**Comment by kanzitelli** [comment]
@fabarea great! Thank you for the kind words 🙏

I have also just updated some UI in [expo-starter](https://github.com/kanzitelli/expo-starter) so it looks better on the web :)
